const list = [
    {
      id: 1,
      title: "First Book of Pencil",
      author: "by Wonder House Books | 25 April 2018",
      price: 89,
      img: "https://friendkit.cssninja.io/assets/img/products/2.svg",
      amount: 1,
    },
    {
      id: 2,
      title: "Panchatantra Stories",
      author: "by Maple Press  | 1 September 2020",
      price: 98,
      img: "https://friendkit.cssninja.io/assets/img/products/1.svg",
      amount: 1,
    },
    {
      id: 3,
      title: "QuestionsAnswers ",
      author: "by Om Books Editorial Team  | 25 November 2018",
      price: 143,
      img: "https://friendkit.cssninja.io/assets/img/products/3.svg",
      amount: 1,
    },
    {
      id: 4,
      title: "Book of Pencil Control",
      author: "by Wonder House Books | 25 April 2018",
      price: 57,
      img: "https://friendkit.cssninja.io/assets/img/products/4.svg",
      amount: 1,
    },
    {
      id: 5,
      title: "My First 1000 Words",
      author: "by Wonder House Books  | 1 January 2018",
      price: 149,
      img: "https://friendkit.cssninja.io/assets/img/products/5.svg",
      amount: 1,
    },
    {
      id: 6,
      title: "101 Panchatantra Stories ",
      author: "by Om Books Editorial Team | 30 September 2020",
      price: 135,
      img: "https://friendkit.cssninja.io/assets/img/products/6.svg",
      amount: 1,
    },
    {
      id: 7,
      title: "School Activities Pack ",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "https://friendkit.cssninja.io/assets/img/products/7.svg",
      amount: 1,
    },
    {
      id: 8,
      title: "Learning Library Pack 1",
      author: "by Wonder House Books  | 6 December 2020",
      price: 289,
      img: "https://friendkit.cssninja.io/assets/img/products/8.svg",
      amount: 1,
    },
    {
      id: 9,
      title: "Story Book for Kids ",
      author: "by Content Team at Target Publications",
      price: 80,
      img: "https://friendkit.cssninja.io/assets/img/products/9.svg",
      amount: 1,
    },
    {
      id: 10,
      title: "Activity Book for Kids",
      author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "https://friendkit.cssninja.io/assets/img/products/10.svg",
      amount: 1,
    },
    {
      id: 11,
      title: "Willy the Silly Panda",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://friendkit.cssninja.io/assets/img/products/11.svg",
      amount: 1,
    },
    {
      id: 12,
      title: "Grandma's Bag of Stories",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://friendkit.cssninja.io/assets/img/products/12.svg",
      amount: 1,
    },
  ];
  
  export default list;